sudo: false
language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - latex-xcolor
    - texlive-base
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-formats-extra
    - texlive-bibtex-extra
    - texlive-humanities
    - texinfo
    - texlive-science
    - latexmk

script:
- pip install -r requirements.txt
- BOOK_VERSION=$(./get-current-version.sh) travis-sphinx build -n -s source
- BOOK_VERSION=$(./get-current-version.sh) make latexpdf
- BOOK_VERSION=$(./get-current-version.sh) make epub
after_success:
- travis-sphinx deploy --cname ssl.cs.luc.edu
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - ./**/SoftwareSystemsLaboratory.pdf
    - ./**/SoftwareSystemsLaboratory.epub
  skip_cleanup: true
  on:
    repo: LoyolaChicagoCS/ssl
    tags: true
